### ISSUE TITLE
Add CMake examples

### ISSUE THREAD

**Issue by srimanachanta** [SleipnirGroup/TrajoptLib#127]
There should be a CMake example for building and using TrajoptLib using Cmake

**Comment by calcmogul** [comment]
The top-level readme documents building TrajoptLib with CMake:
https://github.com/SleipnirGroup/TrajoptLib/?tab=readme-ov-file#c-library

https://cmake.org/cmake/help/latest/#introduction links to https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#guide:Using%20Dependencies%20Guide, which documents using thirdparty libraries in a CMake project.

The examples folder has API usage documentation:
https://github.com/SleipnirGroup/TrajoptLib/blob/main/examples/Examples.md
